/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatest;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import java.util.Scanner;

public class App {

    static ArrayList<String> emailList = new ArrayList<>();
    
    static ArrayList<String> countryNameList = new ArrayList<>();
    static ArrayList<String> countryCodeList = new ArrayList<>();
    static ArrayList<BigInteger> latestPopulation = new ArrayList<>();
    static ArrayList<BigInteger> oneYearEarlier = new ArrayList<>();
    static ArrayList<BigInteger> difference = new ArrayList<>();

    static ArrayList<Country> countryList = new ArrayList<>();

    public static void main(String[] args) {
        String csvFile = "/Users/mariostzialidis/Desktop/Java/JavaAnalyzeData/app/src/main/resources/Population.csv";
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";
        

        try {
            br = new BufferedReader(new FileReader(csvFile));
            while ((line = br.readLine()) != null) {
                String[] values = line.split(cvsSplitBy);

                try {

                    countryNameList.add(values[0]);
                    countryCodeList.add(values[1]);

                    int lastElement = values.length -1;

                    String latestPopulationString = values[lastElement];
                    if(latestPopulationString == "\"\""){
                        latestPopulationString = "0";
                    }
                    BigInteger latestPopulationNumber = new BigInteger(latestPopulationString.replace('"', ' ').trim());
                    
                    latestPopulation.add(latestPopulationNumber);

                    int oneYearEarlierElement = values.length -2;
                    
                    String oneYearEarlierPopulationNumberString = values[oneYearEarlierElement];

                    BigInteger oneYearEarliesNumber = new BigInteger(oneYearEarlierPopulationNumberString.replace('"', ' ').trim());

                    oneYearEarlier.add(oneYearEarliesNumber);

                    BigInteger differencePopulation = latestPopulationNumber.subtract(oneYearEarliesNumber);

                    difference.add(differencePopulation);
                    

                    createCountryObject();

                } catch (NumberFormatException e) {
                    System.out.println("Error: " + e.getMessage());
                    // handle the error in some way
                    
                    e.printStackTrace();
                    throw new RuntimeException("Shit");
                }}

                try {
                    Scanner scanner = new Scanner(System.in);
                    String userInput2;
                
                // keep looping until the user enters valid input
               
                    
                        // prompt the user to enter a country name
                        System.out.print("Enter a country name: ");
                        userInput2 = scanner.nextLine();



                        // loop through the country list and check if the user input matches a country name
                        for (Country country : countryList) {
                            //System.out.println("Scanner Input: " + userInput2);
                            String methode = country.getName().replace('"', ' ').trim();
                           
                            //System.out.println("Methode: " + methode.trim());
                            userInput2 = userInput2.replace('"', ' ').trim();
                            //System.out.println("New One: " + userInput2);
                            if (userInput2.toString().equals(methode)) {
                                System.out.println("Match found: " + methode);

                                String userInput3;
                                System.out.println("Do you want to see more details? (Y/N)");
                                userInput3 = scanner.nextLine();

                                System.out.println(userInput3);

                                scanner.close();

                                if(userInput3 == "N"){
                                    return;
                                }
                                if(userInput3 == "Y"){

                                    System.out.println("Name: " + country.getName().replace('"', ' ').trim());
                                    System.out.println("Country Code: " + country.getCountryCode().replace('"', ' ').trim());
                                    System.out.println("Population : " + country.getLatestPopulation());
                                    System.out.println("On Year Before: " + country.getOneYearEarlier());
                                    System.out.println("Difference compared to year before: " + country.getDifference());
                                }
                            }
                        } 

                        // close the scanner when finished
                        scanner.close();
                


                    } catch (NoSuchElementException e) {
                        // if there is no input available, prompt the user to enter input again
                        System.out.println("No country found");
                    }
                
                
                
               

                
                
                
                //Print everything to the console and check for emails inside the csv file
                /*for (String value : values) {
                    System.out.print(value + "  ");
                    checkForEmail(value);
                }
                System.out.println();
                System.out.println();*/
            
            /* 
            System.out.println();
            if(emailList.isEmpty()){
                System.out.println("No E-Mails found in the .csv file");
            }else{
                System.out.println("These E-Mails were found inside the .csv file");
                for (Object emailObject : emailList) {
                    System.out.println(emailObject);
                }
            }
            System.out.println();

            System.out.println("The dataset returns the following results:");
            System.out.println();
            printDataOfArrayLists();
            returnDataResult();

            printDataOfArrayLists();
            */
            
           
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public static void printDataOfArrayLists(){
        System.out.println(countryNameList.size());
        System.out.println(countryCodeList.size());
        System.out.println(latestPopulation.size());
        System.out.println(oneYearEarlier.size());
        System.out.println(difference.size());
    }

    public static void getDataByIndex(int i){
        System.out.println(countryNameList.get(i));
        System.out.println("Coutry Code: " + countryCodeList.get(i));
        System.out.println("Latest Population: " + latestPopulation.get(i));
        System.out.println("Previous Year Population: " + oneYearEarlier.get(i));
        System.out.println("Difference compared to the previous year: " + difference.get(i));
    }

    public static void returnDataResult(){
        try {
            for(int i = 0; i < countryNameList.size(); i++){

                /* 
                System.out.println(countryNameList.get(i));
                System.out.println("Coutry Code: " + countryCodeList.get(i));
                System.out.println("Latest Population: " + latestPopulation.get(i));
                System.out.println("Previous Year Population: " + oneYearEarlier.get(i));
                System.out.println("Difference compared to the previous year: " + difference.get(i));
                */

                //for (int i = 0; i < countryNameList.size(); i++) {
                    String name = countryNameList.get(i);
                    Country country = new Country(name, countryCodeList.get(i), latestPopulation.get(i), oneYearEarlier.get(i), difference.get(i), i);
                    countryList.add(country);
                
                    System.out.println(country.getName() + " at index " + country.getIndex());
                //}
                
                System.out.println();
                System.out.println("Country Object Methods: ");
            }

            for (Country name : countryList) {
                System.out.println(name.getName());
                System.out.println("Currect Population: " + name.getLatestPopulation());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void createCountryObject(){
        for (int i = 0; i < countryNameList.size(); i++) {
            String name = countryNameList.get(i);
            Country country = new Country(name, countryCodeList.get(i), latestPopulation.get(i), oneYearEarlier.get(i), difference.get(i), i);
            countryList.add(country);
        
            //System.out.println(country.getName() + " at index " + country.getIndex());
        }
    }

    public static void checkForEmail(String input){
        if(input.contains("@")){
            emailList.add(input);
        }
    }
}
